name: Build Devcontainer

on:
  push:
    paths:
      - '.devcontainer/'
  pull_request:
    paths:
      - '.devcontainer/'
  workflow_dispatch:
    inputs:
      PREBUILD_IMG:
        description: 'Docker image'
        required: false
        default: 'vsc-soroban-examples-prebuild'

jobs:
  verify-scripts:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: |
            .devcontainer
      - name: Run Shellcheck
        env:
          SHELLCHECK_OPTS: -s bash
        shell: bash
        run: |
          shellcheck ".devcontainer/ps_autocomplete.sh"
          shellcheck ".devcontainer/pa_welcome.sh"
          shellcheck ".devcontainer/pa_stellar_accounts.sh"

  prebuild:
    name: Docker Build
    runs-on: ubuntu-latest
    environment: devcontainer
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      prebuild: ${{ github.event.inputs.PREBUILD_IMG }}
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: 'false'
          logout: 'false'
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          clean: 'true'
          path: '.'
      - name: QEMU for Multi-Architecture Builds
        uses: docker/setup-qemu-action@v3.6.0
        with:
          cache-image: 'true'
      - name: Buildx Multi-Architecture Builds
        uses: docker/setup-buildx-action@v3.10.0
        with:
          use: true
          driver-opts: image=moby/buildkit:master
          cache-binary: 'true'
          version: "v0.24.0"

      - name: Pre-build Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{env.username}}/${{ env.prebuild }}
          cacheFrom: ${{env.username}}/${{ env.prebuild }}
          cacheTo: ${{env.username}}/${{ env.prebuild }}
          push: always
          checkoutPath: ${{ github.workspace }}
          platform: linux/amd64,linux/arm64




