name: Build Devcontainer

on:
  push:
    paths:
      - '.devcontainer/'
  pull_request:
    paths:
      - '.devcontainer/'
  workflow_dispatch:
    inputs:
      PREBUILD_IMG:
        description: 'Docker image'
        required: false
        default: 'vsc-soroban-examples-prebuild'

jobs:
  verify-scripts:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Shellcheck
        env:
          SHELLCHECK_OPTS: -s bash
        shell: bash
        run: |
          shellcheck ".devcontainer/post_start_cli_autocomplete.sh"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        env:
          BATS_LIB_PATH: NODE_PATH
        with:
          node-version: '22.x'
      - run: |
          echo "export NODE_PATH='/usr/local/bin/:$NODE_PATH'" >> $NODE_PATH
          ls -latr
          npm install -g bats bats-support bats-assert bats-file
          bats .devcontainer/post_start_cli_autocomplete_test.bats
        working-directory: ${{ github.workspace }}

  login:
    name: Docker Login
    runs-on: ubuntu-latest
    environment: devcontainer
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: 'false'
          logout: 'false'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: 'true'
          platforms: 'all'
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: chrisstellar/vsc-soroban-examples-prebuild
          cacheFrom: chrisstellar/vsc-soroban-examples-prebuild
          cacheTo: chrisstellar/vsc-soroban-examples-prebuild
          push: always

