name: Build Devcontainer

on:
  push:
    paths:
      - '.devcontainer/'
  pull_request:
    paths:
      - '.devcontainer/'
  workflow_dispatch:
    inputs:
      DEFAULT_PREBUILD_IMG:
        description: 'Docker image'
        required: false
        default: 'vsc-soroban-examples-prebuild'
      DEFAULT_OCI_IMG:
        description: 'OCI image'
        required: false
        default: 'vsc-soroban-examples-oci'

jobs:
  verify-scripts:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Shellcheck
        env:
          SHELLCHECK_OPTS: -s bash
        shell: bash
        run: |
          shellcheck ".devcontainer/post_start_cli_autocomplete.sh"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: |
          npm -g bats
          bats .devcontainer/post_start_cli_autocomplete_test.bats
        working-directory: ${{ github.workspace }}

  build-docker:
    permissions:
      contents: write
      packages: write
      actions: write
      id-token: write
    name: Devcontainer CLI Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install -g @devcontainers/cli
        working-directory: ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          password: $TOKEN
          ecr: 'false'

      - name: Devcontainer Build
        run: |
          chmod +x ${{github.workspace}}/.devcontainer/tests/build_devcontainer_ci.sh
          ${{github.workspace}}/.devcontainer/tests/build_devcontainer_ci.sh $DEFAULT_PREBUILD_IMG $DEFAULT_OCI_IMG
          
          echo "### Devcontainer CLI Build Successful!!! :rocket:" >> $GITHUB_STEP_SUMMARY
        env:
          BUILDKIT_INLINE_CACHE: 1
          DEFAULT_PREBUILD_IMG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.DEFAULT_PREBUILD_IMG }}
          DEFAULT_OCI_IMG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.DEFAULT_OCI_IMG }}
        working-directory: ${{github.workspace}}
