name: Build Devcontainer

on:
  push:
    paths:
      - '.devcontainer/'
  pull_request:
    paths:
      - '.devcontainer/'
  workflow_dispatch:
    inputs:
      PREBUILD_IMG:
        description: 'Docker image'
        required: false
        default: 'vsc-soroban-examples-prebuild'

jobs:
  verify-scripts:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .devcontainer
      - name: Run Shellcheck
        env:
          SHELLCHECK_OPTS: -s bash
        shell: bash
        run: |
          shellcheck ".devcontainer/ps_autocomplete.sh"
          shellcheck ".devcontainer/pa_welcome.sh"
          shellcheck ".devcontainer/pa_stellar_accounts.sh"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: pnpm
          check-latest: 'true'
      - run: |
          NPM_PREFIX=$(pnpm config list -json | jq -r '.prefix')
          NPM_ROOT=$(pnpm root | echo)
          export BATS_LIB_PATH=${BATS_LIB_PATH:-"${NPM_PREFIX}/lib/node_modules"}
          export BATS_LIB_PATH=${BATS_LIB_PATH:-"${NPM_ROOT}"}
          
          pnpm i bats bats-support bats-assert bats-file && pnpm update
          pnpm exec bats .devcontainer/post_start_cli_autocomplete_test.bats
          ls -latr ${BATS_LIB_PATH}

  prebuild:
    name: Docker Build
    runs-on: ubuntu-latest
    environment: devcontainer
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: 'false'
          logout: 'false'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: 'true'
          path: '.'
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          cache-binary: 'true'
      - name: Pre-build Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{env.username}}/vsc-soroban-examples-prebuild
          cacheFrom: ${{env.username}}/vsc-soroban-examples-prebuild
          push: always
          checkoutPath: ${{ github.workspace }}
          platform: linux/amd64,linux/arm64



