name: Build Devcontainer

on:
  push:
    paths:
      - '.devcontainer/'
  pull_request:
    paths:
      - '.devcontainer/'
  workflow_dispatch:
    inputs:
      PREBUILD_IMG:
        description: 'Docker image'
        required: false
        default: 'vsc-soroban-examples-prebuild'
      OCI_IMG:
        description: 'OCI image'
        required: false
        default: 'vsc-soroban-examples-oci'

jobs:
  verify-scripts:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Shellcheck
        env:
          SHELLCHECK_OPTS: -s bash
        shell: bash
        run: |
          shellcheck ".devcontainer/post_start_cli_autocomplete.sh"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        env:
          BATS_LIB_PATH: NODE_PATH
        with:
          node-version: '22.x'
      - run: |
          echo NODE_PATH > $BATS_LIB_PATH
          ls -latr
          npm install -g bats bats-support bats-assert bats-file
          bats .devcontainer/post_start_cli_autocomplete_test.bats
        working-directory: ${{ github.workspace }}

  login:
    name: Docker Login
    runs-on: ubuntu-latest
    environment: devcontainer
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: 'false'
          logout: 'false'

  build-docker:
    permissions:
      packages: write
      contents: write
    name: Devcontainer Build
    runs-on: ubuntu-latest
    environment: devcontainer
    env:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install -g @devcontainers/cli

      - name: CLI Build
        run: |
          ${{github.workspace}}/.devcontainer/tests/build_devcontainer_ci.sh $PREBUILD $OCI
        env:
          BUILDKIT_INLINE_CACHE: 1
          PREBUILD: ${{ env.username }}/${{ github.event.inputs.PREBUILD_IMG }}
          OCI: ${{ env.username }}/${{ github.event.inputs.OCI_IMG }}
        working-directory: ${{github.workspace}}
